export const ISSUE_PRIORITIES_MAP = {
  NO_COMMUNICATION: 10,
  METER_NOT_ACTIVATED: 20,
  TAMPER: 30,
  POWER_LIMIT_BREACHED: 40,
  OVER_VOLTAGE: 50,
  LOW_VOLTAGE: 60,
  POWER_LIMIT_BAD_CONFIGURATION: 70,
  METER_STATE_BAD_CONFIGURATION: 80,
  UNEXPECTED_POWER_LIMIT: 70,
  UNEXPECTED_METER_STATUS: 80,
  NO_CREDIT: 90,
  NO_CONSUMPTION: 100,
};
