import moment from 'moment';

export const START_OF_MONTH = moment().startOf('month');

// 3 FS, 1 HPS
export const metersLosingMoney = [
  {
    id: 123,
    meter_type: 'FS',
    created_at: '2022-11-22T08:07:52.000Z',
    external_reference: '47001771477',
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    nickname: null,
    meter_phase: 'SINGLE_PHASE',
    last_metering_hardware_install_session_id: null,
    dcu_id: 123,
    connection_id: 3333,
    last_encountered_issue: {
      created_at: START_OF_MONTH.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
      issue_type: 'NO_CONSUMPTION',
      issue_status: 'OPEN',
    },
  },
  {
    id: 456,
    meter_type: 'FS',
    created_at: '2022-11-22T08:07:52.000Z',
    external_reference: '47001771477',
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    nickname: null,
    meter_phase: 'SINGLE_PHASE',
    last_metering_hardware_install_session_id: null,
    is_simulated: 0,
    dcu_id: 123,
    connection_id: 3333,
    last_encountered_issue: {
      created_at: START_OF_MONTH.add(8, 'hours').format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
      issue_type: 'NO_CONSUMPTION',
      issue_status: 'OPEN',
    },
  },
  {
    id: 789,
    meter_type: 'FS',
    is_on: 0,
    should_be_on: 0,
    is_on_updated_at: '2023-12-04T17:05:25.000Z',
    voltage: 226.18,
    power: 0,
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    meter_phase: 'SINGLE_PHASE',
    last_metering_hardware_install_session_id: null,
    dcu_id: 123,
    connection_id: 3333,
    last_encountered_issue: {
      created_at: START_OF_MONTH.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
      issue_type: 'NO_CREDIT',
      issue_status: 'OPEN',
    },
  },
  {
    id: 112,
    meter_type: 'HPS',
    kwh: 0,
    kwh_updated_at: null,
    is_on: 0,
    voltage: 226.18,
    voltage_updated_at: '2023-11-28T17:24:10.000Z',
    power: 0,
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    meter_phase: 'SINGLE_PHASE',
    is_simulated: 0,
    dcu_id: 123,
    connection_id: 3333,
    last_encountered_issue: {
      created_at: START_OF_MONTH.format('YYYY-MM-DDTHH:mm:ss.SSS[Z]'),
      issue_type: 'NO_CREDIT',
      issue_status: 'CLOSED',
      closed_at: START_OF_MONTH.add(2, 'days').toDate(),
    },
  },
];

export const metersMakingMoney = [
  {
    id: 222,
    meter_type: 'FS',
    is_on: 0,
    should_be_on: 0,
    voltage: 226.18,
    power: 0,
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    pole_id: null,
    meter_phase: 'SINGLE_PHASE',
    last_metering_hardware_install_session_id: null,
    kwh_tariff: null,
    last_encountered_issue: null,
  },
  {
    id: 223,
    meter_type: 'HPS',
    created_at: '2022-11-22T08:07:52.000Z',
    external_reference: '47001771477',
    kwh: 0,
    is_on: 0,
    should_be_on: 0,
    voltage: 226.18,
    power: 0,
    latitude: 9.65698,
    longitude: 13.2223,
    coord_accuracy: 1.861,
    power_limit: 0,
    external_system: 'CALIN',
    meter_phase: 'SINGLE_PHASE',
    last_metering_hardware_install_session_id: null,
    last_encountered_issue: {
      closed_at: START_OF_MONTH.subtract(31, 'days').toDate(),
      issue_type: 'NO_CONSUMPTION',
      issue_status: 'CLOSED',
    },
  },
];

export const mockMeters = [ ...metersLosingMoney, ...metersMakingMoney ];

