// import { supabase } from '@core/modules/supabase.module';
// import { QueryData } from '@supabase/supabase-js';

export const orderForMetaQueryBrutal = `
  *,
  author:accounts!author_id(
    *,
    member:members(id),
    agent:agents(id),
    customer:customers(id)
  ),
  sender_wallet:wallets!sender_wallet_id(
    *,
    agent:agents(
      *,
      account:accounts(*),
      grid:grids(*)
    ),
    meter:meters(
      *,
      connection:connections(
        customer:customers(
          account:accounts(*),
          grid:grids(*)
        )
      )
    ),
    organization:organizations!organization_id(*),
    connection:connections(
      *,
      customer:customers(
        *,
        account:accounts(*),
        grid:grids(*)
      )
    )
  ),
  receiver_wallet:wallets!receiver_wallet_id(
    agent:agents(
      *,
      account:accounts(*),
      grid:grids(*)
    ),
    customer:customers(
      *,
      account:accounts(*),
      grid:grids(*)
    ),
    organization:organizations!organization_id(*),
    meter:meters(
      *,
      connection:connections(
        customer:customers(
          *,
          account:accounts(*),
          grid:grids(*)
        )
      )
    ),
    connection:connections(
      *,
      customer:customers(
        *,
        account:accounts(*),
        grid:grids(*)
      )
    )
  )
`;

export const orderForMetaQuerySpecific = `
  id,
  meter_credit_transfer_id,
  author:accounts!author_id(
    full_name,
    member:members(id),
    agent:agents(id),
    customer:customers(id)
  ),
  sender_wallet:wallets!sender_wallet_id(
    identifier,
    agent:agents(
      id,
      account:accounts(full_name),
      grid:grids(
        id,
        organization_id
      )
    ),
    meter:meters(
      id,
      external_reference,
      connection:connections(
        customer:customers(
          account:accounts(full_name),
          grid:grids(
            id,
            organization_id
          )
        )
      )
    ),
    organization:organizations!organization_id(
      id,
      name
    ),
    connection:connections(
      id,
      upload_uuid,
      customer:customers(
        is_hidden_from_reporting,
        account:accounts(full_name),
        grid:grids(
          id,
          organization_id,
          is_hidden_from_reporting
        )
      )
    )
  ),
  receiver_wallet:wallets!receiver_wallet_id(
    agent:agents(
      id,
      account:accounts(full_name),
      grid:grids(
        id,
        organization_id,
        is_hidden_from_reporting
      )
    ),
    customer:customers(
      id,
      account:accounts(full_name),
      is_hidden_from_reporting,
      grid:grids(
        id,
        organization_id,
        is_hidden_from_reporting
      )
    ),
    organization:organizations!organization_id(
      id,
      name
    ),
    meter:meters(
      id,
      external_reference,
      connection:connections(
        customer:customers(
          id,
          is_hidden_from_reporting,
          account:accounts(full_name),
          grid:grids(
            id,
            organization_id,
            is_hidden_from_reporting
          )
        )
      )
    ),
    connection:connections(
      id,
      upload_uuid,
      customer:customers(
        id,
        is_hidden_from_reporting,
        account:accounts(full_name),
        grid:grids(
          id,
          organization_id,
          is_hidden_from_reporting
        )
      )
    )
  )
`;

export const orderForMetaQuery = orderForMetaQuerySpecific;
// @TYPING-PERFORMANCE :: This generated type is very complex and slows down TS. Use only when actively developing Order metadata
// const _orderForMetaQuery = supabase.from('orders').select(orderForMetaQuerySpecific).single();
export type OrderForMeta = any; //QueryData<typeof _orderForMetaQuery>;
